export const firstProductCard = 'article.relative.flex.flex-col';
export const addToCartButtonInCard = 'button:contains("AÑADIR AL CARRITO")'; 
//export const elements = { cartIcon: '[data-at="cart-opener"]'};
//export const cartElements = { cartIcon: '[data-at="cart-opener"]' };
//export const elements = {cartIcon: '[data-at="cart-opener"]',};
export const cartIcon = '[data-at="cart-opener"]';
export const checkoutButton = 'button:contains("Ir al checkout")';
export const cartImage = 'img';
export const quantityCell = 'td:contains("1")';
export const priceCell = 'td:matches(/^\\$\\d+(\\.\\d{2})?$/)';
export const totalText = 'contains(/^Total: \\$\\d+(\\.\\d{2})?$/)';
