//export const homeMainTitle = 'Déjate llevar por el camino';
export const homeMainTitle = '[data-at="brand-logo"] span' ;
export const accederLink = 'Acceder';
export const loginTitle = 'Inicia Sesión';
export const emailInput = 'input[name="email"]';
export const passwordInput = 'input[name="password"]';
export const loginButton = 'button:contains("Iniciar Sesión")';
export const logoutLink = 'Cerrar Sesión';
export const errorModalText = 'No pudimos iniciar sesión con estas credenciales';
export const volverButton = 'Volver';
